// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rate.proto

package rate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	HotelIds             []string `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	InDate               string   `protobuf:"bytes,2,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,3,opt,name=outDate,proto3" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_rate_8f247c131e973f5e, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHotelIds() []string {
	if m != nil {
		return m.HotelIds
	}
	return nil
}

func (m *Request) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *Request) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type Result struct {
	RatePlans            []*RatePlan `protobuf:"bytes,1,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_rate_8f247c131e973f5e, []int{1}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetRatePlans() []*RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

type RatePlan struct {
	HotelId              string    `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	Code                 string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	InDate               string    `protobuf:"bytes,3,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string    `protobuf:"bytes,4,opt,name=outDate,proto3" json:"outDate,omitempty"`
	RoomType             *RoomType `protobuf:"bytes,5,opt,name=roomType,proto3" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RatePlan) Reset()         { *m = RatePlan{} }
func (m *RatePlan) String() string { return proto.CompactTextString(m) }
func (*RatePlan) ProtoMessage()    {}
func (*RatePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_rate_8f247c131e973f5e, []int{2}
}
func (m *RatePlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatePlan.Unmarshal(m, b)
}
func (m *RatePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatePlan.Marshal(b, m, deterministic)
}
func (dst *RatePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatePlan.Merge(dst, src)
}
func (m *RatePlan) XXX_Size() int {
	return xxx_messageInfo_RatePlan.Size(m)
}
func (m *RatePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_RatePlan.DiscardUnknown(m)
}

var xxx_messageInfo_RatePlan proto.InternalMessageInfo

func (m *RatePlan) GetHotelId() string {
	if m != nil {
		return m.HotelId
	}
	return ""
}

func (m *RatePlan) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RatePlan) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *RatePlan) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

func (m *RatePlan) GetRoomType() *RoomType {
	if m != nil {
		return m.RoomType
	}
	return nil
}

type RoomType struct {
	BookableRate         float64  `protobuf:"fixed64,1,opt,name=bookableRate,proto3" json:"bookableRate,omitempty"`
	TotalRate            float64  `protobuf:"fixed64,2,opt,name=totalRate,proto3" json:"totalRate,omitempty"`
	TotalRateInclusive   float64  `protobuf:"fixed64,3,opt,name=totalRateInclusive,proto3" json:"totalRateInclusive,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	RoomDescription      string   `protobuf:"bytes,6,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomType) Reset()         { *m = RoomType{} }
func (m *RoomType) String() string { return proto.CompactTextString(m) }
func (*RoomType) ProtoMessage()    {}
func (*RoomType) Descriptor() ([]byte, []int) {
	return fileDescriptor_rate_8f247c131e973f5e, []int{3}
}
func (m *RoomType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomType.Unmarshal(m, b)
}
func (m *RoomType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomType.Marshal(b, m, deterministic)
}
func (dst *RoomType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomType.Merge(dst, src)
}
func (m *RoomType) XXX_Size() int {
	return xxx_messageInfo_RoomType.Size(m)
}
func (m *RoomType) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomType.DiscardUnknown(m)
}

var xxx_messageInfo_RoomType proto.InternalMessageInfo

func (m *RoomType) GetBookableRate() float64 {
	if m != nil {
		return m.BookableRate
	}
	return 0
}

func (m *RoomType) GetTotalRate() float64 {
	if m != nil {
		return m.TotalRate
	}
	return 0
}

func (m *RoomType) GetTotalRateInclusive() float64 {
	if m != nil {
		return m.TotalRateInclusive
	}
	return 0
}

func (m *RoomType) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RoomType) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *RoomType) GetRoomDescription() string {
	if m != nil {
		return m.RoomDescription
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "rate.Request")
	proto.RegisterType((*Result)(nil), "rate.Result")
	proto.RegisterType((*RatePlan)(nil), "rate.RatePlan")
	proto.RegisterType((*RoomType)(nil), "rate.RoomType")
}

func init() { proto.RegisterFile("proto/rate.proto", fileDescriptor_rate_8f247c131e973f5e) }

var fileDescriptor_rate_8f247c131e973f5e = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x4a, 0xfb, 0x30,
	0x14, 0xc7, 0xc9, 0x6f, 0xfd, 0x75, 0xed, 0x71, 0xfe, 0xe1, 0x5c, 0x48, 0x18, 0x5e, 0x8c, 0xde,
	0x38, 0x44, 0x36, 0x98, 0xe0, 0x13, 0x0c, 0x64, 0x77, 0x72, 0x10, 0xbc, 0xee, 0xba, 0x80, 0xc5,
	0xd8, 0xd4, 0x24, 0x15, 0xf6, 0x22, 0x3e, 0x9a, 0xcf, 0x23, 0x49, 0xd3, 0xae, 0x13, 0xbd, 0x3b,
	0x9f, 0xef, 0x09, 0xa7, 0x9f, 0xa4, 0x07, 0x2e, 0x6a, 0xad, 0xac, 0x5a, 0xea, 0xdc, 0x8a, 0x85,
	0x2f, 0x31, 0x72, 0x75, 0xf6, 0x0c, 0x63, 0x12, 0xef, 0x8d, 0x30, 0x16, 0xa7, 0x90, 0xbc, 0x28,
	0x2b, 0xe4, 0x66, 0x67, 0x38, 0x9b, 0x8d, 0xe6, 0x29, 0xf5, 0x8c, 0x97, 0x10, 0x97, 0xd5, 0x3a,
	0xb7, 0x82, 0xff, 0x9b, 0xb1, 0x79, 0x4a, 0x81, 0x90, 0xc3, 0x58, 0x35, 0xd6, 0x37, 0x46, 0xbe,
	0xd1, 0x61, 0x76, 0x0f, 0x31, 0x09, 0xd3, 0x48, 0x8b, 0xb7, 0x90, 0xba, 0x4f, 0x3d, 0xca, 0xbc,
	0x6a, 0x07, 0x9f, 0xac, 0xce, 0x16, 0x5e, 0x84, 0x42, 0x4c, 0x87, 0x03, 0xd9, 0x27, 0x83, 0xa4,
	0xcb, 0xdd, 0xf8, 0xa0, 0xc0, 0x59, 0x3b, 0x3e, 0x20, 0x22, 0x44, 0x85, 0xda, 0x75, 0x3a, 0xbe,
	0x1e, 0x48, 0x8e, 0xfe, 0x92, 0x8c, 0x8e, 0x24, 0xf1, 0x06, 0x12, 0xad, 0xd4, 0xdb, 0xd3, 0xbe,
	0x16, 0xfc, 0xff, 0x8c, 0x0d, 0xcc, 0x42, 0x4a, 0x7d, 0x3f, 0xfb, 0x72, 0x62, 0x01, 0x30, 0x83,
	0xc9, 0x56, 0xa9, 0xd7, 0x7c, 0x2b, 0x85, 0x93, 0xf5, 0x76, 0x8c, 0x8e, 0x32, 0xbc, 0x82, 0xd4,
	0x2a, 0x9b, 0x4b, 0xea, 0x9e, 0x8d, 0xd1, 0x21, 0xc0, 0x05, 0x60, 0x0f, 0x9b, 0xaa, 0x90, 0x8d,
	0x29, 0x3f, 0x5a, 0x71, 0x46, 0xbf, 0x74, 0xfa, 0x0b, 0x47, 0x83, 0x0b, 0x4f, 0x21, 0x29, 0x1a,
	0xad, 0x45, 0x55, 0xec, 0xbd, 0x7e, 0x4a, 0x3d, 0xe3, 0x1c, 0xce, 0x9d, 0xfa, 0x5a, 0x98, 0x42,
	0x97, 0xb5, 0x2d, 0x55, 0xc5, 0x63, 0x7f, 0xe4, 0x67, 0xbc, 0x5a, 0x42, 0xe4, 0x8d, 0xae, 0x21,
	0x79, 0x10, 0xd6, 0x95, 0x06, 0x4f, 0xc3, 0x33, 0xb4, 0xab, 0x31, 0x9d, 0x74, 0xe8, 0x7e, 0xe8,
	0x36, 0xf6, 0x0b, 0x74, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x2a, 0xa1, 0x90, 0x54, 0x02,
	0x00, 0x00,
}
