// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hotel.proto

package hotel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "go-micro-consul-cluster/srv/profile/proto"
import proto2 "go-micro-consul-cluster/srv/rate/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Reqeust struct {
	InDate               string   `protobuf:"bytes,1,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,2,opt,name=outDate,proto3" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reqeust) Reset()         { *m = Reqeust{} }
func (m *Reqeust) String() string { return proto.CompactTextString(m) }
func (*Reqeust) ProtoMessage()    {}
func (*Reqeust) Descriptor() ([]byte, []int) {
	return fileDescriptor_hotel_e50cb15b21d087e6, []int{0}
}
func (m *Reqeust) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reqeust.Unmarshal(m, b)
}
func (m *Reqeust) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reqeust.Marshal(b, m, deterministic)
}
func (dst *Reqeust) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reqeust.Merge(dst, src)
}
func (m *Reqeust) XXX_Size() int {
	return xxx_messageInfo_Reqeust.Size(m)
}
func (m *Reqeust) XXX_DiscardUnknown() {
	xxx_messageInfo_Reqeust.DiscardUnknown(m)
}

var xxx_messageInfo_Reqeust proto.InternalMessageInfo

func (m *Reqeust) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *Reqeust) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type Response struct {
	Hotels               []*proto1.Hotel    `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	RatePlans            []*proto2.RatePlan `protobuf:"bytes,2,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_hotel_e50cb15b21d087e6, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHotels() []*proto1.Hotel {
	if m != nil {
		return m.Hotels
	}
	return nil
}

func (m *Response) GetRatePlans() []*proto2.RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

func init() {
	proto.RegisterType((*Reqeust)(nil), "hotel.Reqeust")
	proto.RegisterType((*Response)(nil), "hotel.Response")
}

func init() { proto.RegisterFile("proto/hotel.proto", fileDescriptor_hotel_e50cb15b21d087e6) }

var fileDescriptor_hotel_e50cb15b21d087e6 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4f, 0x84, 0x30,
	0x10, 0x85, 0x65, 0x0d, 0xac, 0x3b, 0x26, 0x18, 0x7b, 0x30, 0x0d, 0x27, 0xc2, 0x41, 0x89, 0x51,
	0x9a, 0xc0, 0xd1, 0xab, 0x07, 0x8f, 0xa6, 0xbf, 0x40, 0x30, 0x55, 0x1b, 0xb1, 0x83, 0x6d, 0xf1,
	0xf7, 0x9b, 0x4e, 0x8b, 0x1e, 0xf6, 0x36, 0x6f, 0xde, 0x7b, 0xe9, 0xd7, 0x81, 0xcb, 0xc5, 0xa2,
	0x47, 0xf1, 0x81, 0x5e, 0xcd, 0x1d, 0xcd, 0x2c, 0x27, 0x51, 0xdd, 0x7f, 0xe9, 0x57, 0x8b, 0x62,
	0x42, 0xfc, 0xd4, 0xe6, 0x5d, 0x38, 0xfb, 0x23, 0x16, 0x8b, 0x6f, 0x7a, 0x56, 0x22, 0x76, 0x92,
	0x8a, 0xad, 0xea, 0xe6, 0x38, 0x6e, 0x47, 0xbf, 0x65, 0xc3, 0x18, 0x83, 0xcd, 0x03, 0xec, 0xa5,
	0xfa, 0x56, 0xab, 0xf3, 0xec, 0x0a, 0x0a, 0x6d, 0x1e, 0x47, 0xaf, 0x78, 0x56, 0x67, 0xed, 0x41,
	0x26, 0xc5, 0x38, 0xec, 0x71, 0xf5, 0x64, 0xec, 0xc8, 0xd8, 0x64, 0xf3, 0x02, 0x67, 0x52, 0xb9,
	0x05, 0x8d, 0x53, 0xec, 0x1a, 0x0a, 0x22, 0x75, 0x3c, 0xab, 0x4f, 0xdb, 0xf3, 0xbe, 0xec, 0x36,
	0xa2, 0xa7, 0xb0, 0x96, 0xc9, 0x65, 0x77, 0x70, 0x08, 0xcf, 0x3f, 0xcf, 0xa3, 0x71, 0x7c, 0x97,
	0xa2, 0x04, 0x24, 0xd3, 0x5a, 0xfe, 0x07, 0xfa, 0x01, 0x72, 0xaa, 0xb3, 0x5b, 0xc8, 0x83, 0xef,
	0x58, 0xd9, 0xc5, 0xeb, 0x24, 0xea, 0xea, 0xe2, 0x4f, 0x47, 0x90, 0xe6, 0x64, 0x2a, 0xe8, 0x6b,
	0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xb5, 0xdb, 0xd7, 0x4e, 0x01, 0x00, 0x00,
}
